## Following line defines used openwrt repository.
## It is commented out because it is not feed but is used by compile_pkgs script.
# openwrt https://openwrt.turris.cz/openwrt/openwrt.git^4da53efc2fe744601e6189492dbd06b8930d72b8

src-git-full turrispackages https://gitlab.nic.cz/turris/os/packages.git;temp/tos10
src-git-full node https://openwrt.turris.cz/nxhack/openwrt-node-packages.git;openwrt-25.12
src-git-full packages https://openwrt.turris.cz/feed/packages.git^506c37591d7cd9b3cfd812e69e708349268f9865
src-git-full luci https://openwrt.turris.cz/project/luci.git^27a9c0c94264063894d40420956696d19b175744
src-git-full routing https://openwrt.turris.cz/feed/routing.git^662b57dff7d20634f2b8676400cf4299611cfe4b
src-git-full telephony https://openwrt.turris.cz/feed/telephony.git^2618106d5846a4a542fdf5809f0d3ed228ce439b
src-git-full cesnet https://openwrt.turris.cz/CESNET/Nemea-OpenWRT.git

## Following line is not feed but it is used in generate_lists script.
# updater-lists https://gitlab.nic.cz/turris/os/updater-lists.git;develop
