## Following line defines used openwrt repository.
## It is commented out because it is not feed but is used by compile_pkgs script.
# openwrt https://openwrt.turris.cz/openwrt/openwrt.git;openwrt-24.10

src-git-full turrispackages https://gitlab.nic.cz/turris/os/packages.git;master
src-git-full node https://openwrt.turris.cz/nxhack/openwrt-node-packages.git;openwrt-24.10
src-git-full packages https://openwrt.turris.cz/feed/packages.git^8dda4c85f9603461c95ac21d9ca267ab7cbb405d
src-git-full luci https://openwrt.turris.cz/project/luci.git;openwrt-24.10
src-git-full routing https://openwrt.turris.cz/feed/routing.git;openwrt-24.10
src-git-full telephony https://openwrt.turris.cz/feed/telephony.git;openwrt-24.10
src-git-full video https://git.openwrt.org/feed/video.git;openwrt-24.10
src-git-full cesnet https://openwrt.turris.cz/CESNET/Nemea-OpenWRT.git

## Following line is not feed but it is used in generate_lists script.
# updater-lists https://gitlab.nic.cz/turris/os/updater-lists.git;master
