## Following line defines used openwrt repository.
## It is commented out because it is not feed but is used by compile_pkgs script.
# openwrt https://openwrt.turris.cz/openwrt/openwrt.git^5774c8b316eff80070775ee695d998ad3ee828d1

src-git-full turrispackages https://gitlab.nic.cz/turris/os/packages.git^eacb1a970e83d831461793aceb9e3254a7ddd8ee
src-git-full node https://openwrt.turris.cz/nxhack/openwrt-node-packages.git^c50e8e07be978a5fed7bee3edc9a24c598a968e4
src-git-full packages https://openwrt.turris.cz/feed/packages.git^8dda4c85f9603461c95ac21d9ca267ab7cbb405d
src-git-full luci https://openwrt.turris.cz/project/luci.git^ec3d81891b2399829f0254c7b4b6db336619cbdb
src-git-full routing https://openwrt.turris.cz/feed/routing.git^3eb59e9471858c83891979793f1dd29cca156919
src-git-full telephony https://openwrt.turris.cz/feed/telephony.git^2a4541d46199ac96fac214d02c908402831c4dc6
src-git-full video https://git.openwrt.org/feed/video.git^44dc7f3a1f7157d55817002eb4a5f3a59de65d67
src-git-full cesnet https://openwrt.turris.cz/CESNET/Nemea-OpenWRT.git^9fb88f1af924a032fa832a6658c601ce10a3c304

## Following line is not feed but it is used in generate_lists script.
# updater-lists https://gitlab.nic.cz/turris/os/updater-lists.git^abcb265fac73d69058137519c27476256c440f9b
