Simple Turris OS building script
================================

Getting started
---------------

Create an empty directory you want to build Turris OS in, enter that directory
and from it call `compile_fw` script. In most basic use-case, this should be
enough. Be aware - *it will delete all previous content of the current
directory*. You can repeat individual steps of the compilation separately,
check `compile_fw help` for a list of available commands, generic options and
their brief descriptions.

Advanced usage
--------------

Patching
~~~~~~~~

If you need to patch OpenWRT or any of the feeds, put a git formatted patch
into respective subdirectory of patches directory. In patches directory, there
is openwrt directory and directory for each feed we are patching. Inside those
directories, patches are also divided into subdirectories like `to-upstream`,
`wip` or `hack` to somehow distinguish between quality of patches.

Configuration
~~~~~~~~~~~~~

Default config for OpenWRT is put in `configs` directory either in directory
`common` or in a directory named after the target board. Files in those
directories gets merged (common ones first) and will form the final `.config`
file. Some parts of `compile_fw` might modify it further.

Release notes
~~~~~~~~~~~~~

There is a `NEWS` file in this directory that contains version number and after
it lines with new features in the release. This file is used to generate
`turris-version` package. `compile_fw` script reads it, finds the newest
version and from notes underneath it creates the package with release notes.
